name: Ubuntu (clang)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    strategy:
      matrix:
        mode: [ Debug, Release ]
    runs-on: ubuntu-22.04
    
    steps:
    - name: check out
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install curl libssl-dev libcurl4-openssl-dev libmxml-dev libapr1-dev libaprutil1-dev
              
    - name: configure cmake
      run: CXX=clang++ CC=clang cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
      
    - name: build project
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.mode }}

  
